import { Document as DocxDocument, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { RenderedDocument, StyleConfig } from '../rendering/renderingEngine.js';
import { DocumentExporter } from './exportTypes.js';
import { ExportError } from '../../errors/customErrors.js';

export class DocxExporter implements DocumentExporter {
  public async export(doc: RenderedDocument, style: StyleConfig): Promise<Buffer> {
    try {
      // In a real application, we would use an HTML-to-Docx parser. 
      // For this MVP, we parse the lines of raw markdown content and map them to docx objects.
      // doc.html has the HTML representation, but raw markdown is much cleaner to parse into docx structure.
      // We will parse docx elements.
      const lines = doc.html.split('\n');
      const children: any[] = [];

      // Add a header/title if configured
      if (style.headerText) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: style.headerText, size: 16, color: '6b7280' })],
            alignment: AlignmentType.RIGHT,
          })
        );
      }

      // Add Document Title
      children.push(
        new Paragraph({
          text: doc.title,
          heading: HeadingLevel.TITLE,
          spacing: { after: 200 },
        })
      );

      // Parse lines
      let inList = false;

      // We'll read the intermediate HTML elements for robust mapping, 
      // or we can parse the content line-by-line. A robust way is to parse lines and look for tags or standard Markdown.
      // Since doc.html contains standard HTML tags generated by parseMarkdownToHtml, we can match regex tags!
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;

        // Header 1
        if (trimmed.startsWith('<h1')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              text,
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 240, after: 120 },
            })
          );
        }
        // Header 2
        else if (trimmed.startsWith('<h2')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              text,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            })
          );
        }
        // Header 3
        else if (trimmed.startsWith('<h3')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              text,
              heading: HeadingLevel.HEADING_3,
              spacing: { before: 180, after: 80 },
            })
          );
        }
        // Blockquote
        else if (trimmed.startsWith('<blockquote')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              children: [new TextRun({ text, italics: true, color: '4b5563' })],
              indent: { left: 720 },
              spacing: { before: 120, after: 120 },
            })
          );
        }
        // List Item
        else if (trimmed.startsWith('<li>')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              text,
              bullet: { level: 0 },
              spacing: { after: 100 },
            })
          );
        }
        // Code Block
        else if (trimmed.startsWith('<pre')) {
          const text = this.stripTags(trimmed);
          children.push(
            new Paragraph({
              children: [new TextRun({ text, font: 'Courier New', size: 20 })],
              spacing: { before: 100, after: 100 },
            })
          );
        }
        // Regular Paragraph
        else if (trimmed.startsWith('<p')) {
          const text = this.stripTags(trimmed);
          // Inline parsing for bold/italics in paragraph could be added here
          children.push(
            new Paragraph({
              children: [new TextRun({ text, size: 22 })],
              spacing: { after: 150 },
            })
          );
        }
      }

      // Add a footer if configured
      if (style.footerText) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: style.footerText, size: 16, color: '6b7280' })],
            alignment: AlignmentType.RIGHT,
            spacing: { before: 200 },
          })
        );
      }

      const docx = new DocxDocument({
        sections: [
          {
            properties: {
              page: {
                margin: {
                  top: style.marginSize !== undefined ? style.marginSize * 20 : 1440, // convert px to DXA
                  bottom: style.marginSize !== undefined ? style.marginSize * 20 : 1440,
                  left: style.marginSize !== undefined ? style.marginSize * 20 : 1440,
                  right: style.marginSize !== undefined ? style.marginSize * 20 : 1440,
                },
                size: {
                  orientation: style.orientation,
                },
              },
            },
            children,
          },
        ],
      });

      return await Packer.toBuffer(docx);
    } catch (error: any) {
      throw new ExportError(`Failed to generate DOCX file: ${error.message}`, error);
    }
  }

  private stripTags(html: string): string {
    return html.replace(/<[^>]*>/g, '').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
  }
}
