import JSZip from 'jszip';
import crypto from 'crypto';
import { RenderedDocument, StyleConfig } from '../rendering/renderingEngine.js';
import { DocumentExporter } from './exportTypes.js';
import { ExportError } from '../../errors/customErrors.js';

export class EpubExporter implements DocumentExporter {
  public async export(doc: RenderedDocument, style: StyleConfig): Promise<Buffer> {
    try {
      const zip = new JSZip();
      const uuid = crypto.randomUUID();
      const title = doc.title;

      // 1. mimetype (Must be first, and stored uncompressed)
      // JSZip options.compression = "STORE" means no compression
      zip.file('mimetype', 'application/epub+zip', { compression: 'STORE' });

      // 2. META-INF/container.xml
      const containerXml = `<?xml version="1.0" encoding="UTF-8" ?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`;
      zip.folder('META-INF')?.file('container.xml', containerXml);

      // 3. OEBPS/stylesheet.css
      // We can use the styles generated by compileStyles
      zip.folder('OEBPS')?.file('stylesheet.css', doc.styles);

      // 4. OEBPS/content.xhtml (Must be well-formed XML/XHTML)
      // We clean the html content to be XML-compliant
      const xhtmlContent = this.convertToXhtml(doc.html);
      const contentXhtml = `<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>${title}</title>
    <link rel="stylesheet" href="stylesheet.css" type="text/css"/>
  </head>
  <body>
    <div class="content-wrapper">
      <h1>${title}</h1>
      ${xhtmlContent}
    </div>
  </body>
</html>`;
      zip.folder('OEBPS')?.file('content.xhtml', contentXhtml);

      // 5. OEBPS/content.opf (Manifest)
      const contentOpf = `<?xml version="1.0" encoding="UTF-8" ?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookID" version="2.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title>${title}</dc:title>
    <dc:language>en</dc:language>
    <dc:identifier id="BookID">urn:uuid:${uuid}</dc:identifier>
    <dc:creator>DocForge AI</dc:creator>
    <dc:publisher>DocForge AI Platform</dc:publisher>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="content" href="content.xhtml" media-type="application/xhtml+xml"/>
    <item id="stylesheet" href="stylesheet.css" media-type="text/css"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="content"/>
  </spine>
</package>`;
      zip.folder('OEBPS')?.file('content.opf', contentOpf);

      // 6. OEBPS/toc.ncx (Table of Contents)
      const tocNcx = `<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ncx PUBLIC "-//NISO//DTD NCX 2005-1//EN" "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="urn:uuid:${uuid}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle>
    <text>${title}</text>
  </docTitle>
  <navMap>
    <navPoint id="navpoint-1" playOrder="1">
      <navLabel>
        <text>${title}</text>
      </navLabel>
      <content src="content.xhtml"/>
    </navPoint>
  </navMap>
</ncx>`;
      zip.folder('OEBPS')?.file('toc.ncx', tocNcx);

      // Generate EPUB zip file buffer
      const epubBuffer = await zip.generateAsync({
        type: 'nodebuffer',
        mimeType: 'application/epub+zip',
        compression: 'DEFLATE',
      });

      return epubBuffer;
    } catch (error: any) {
      throw new ExportError(`Failed to generate EPUB package: ${error.message}`, error);
    }
  }

  private convertToXhtml(html: string): string {
    // Basic conversion to ensure tags like img, br, input are closed for XML compliance
    let xhtml = html;
    xhtml = xhtml.replace(/<img([^>]*)(?<!\/)>/g, '<img$1 />');
    xhtml = xhtml.replace(/<br([^>]*)(?<!\/)>/g, '<br$1 />');
    xhtml = xhtml.replace(/<hr([^>]*)(?<!\/)>/g, '<hr$1 />');
    return xhtml;
  }
}
